# Freemarker / Http
spring :
    http :
        encoding :
            charset : UTF-8
            enabled : true
    session :
        store-type : HASH_MAP

    freemarker :
        cache : false
        charset : UTF-8
        check-template-location : true
        content-type : text/html
        prefix : /_template/
        suffix : .ftl
        template-loader-path : classpath:/templates/_freemarker/
        settings :
            default_encoding : UTF-8
            datetime_format : yyyy-MM-dd
            number_format : 0.###

    cache :
        ehcache :
        config : classpath:/conf/cache/ehcache-config.xml

security :
    #user:
      #name : user
      #password : test
    oauth2 :
        #client :
            #clientId: foo
            #clientSecret: bar
            #authorized-grant-types: authorization_code,refresh_token,password
            #scope: read
        authorization:
            check-token-access: isAuthenticated()
            #token-key-access: isAuthenticated()
        #resource:
            #jwt:
                #key-value: jwt_key_test
---

# Server Setting
server :
    session :
        timeout : 1800
    tomcat :
        uri-encoding : UTF-8
    servlet-path : /*
    port: 8080

spring:
    profiles:
      active: local
    first :
        datasource:
            url : jdbc:mysql://localhost:3306/OAUTH_PRO?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000
    second :
        datasource:
            url : jdbc:mysql://localhost:3306/OAUTH_PRO?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000
#    jpa:
#      hibernate:
#        ddl-auto: update
#       naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      show-sql: false


# Actuator 읽기 인증 제거
management :
    security :
        enabled : false