# Freemarker / Http
spring :
    http :
        encoding :
            charset : UTF-8
            enabled : true
    session :
        store-type : HASH_MAP

    freemarker :
        cache : false
        charset : UTF-8
        check-template-location : true
        content-type : text/html
        prefix : /_template/
        suffix : .ftl
        template-loader-path : classpath:/templates/_freemarker/
        settings :
            default_encoding : UTF-8
            datetime_format : yyyy-MM-dd
            number_format : 0.###

    cache :
        ehcache :
        config : classpath:/conf/cache/ehcache-config.xml

security :
    oauth2 :
        client :
            client-id: your_client_id
            client-secret: your_client_secret
            #authorized-grant-types: authorization_code,refresh_token,password
            #scope: member.info.public
        resource:
            token-info-uri: http://localhost:9090/oauth/check_token
            #jwt:
                #key-uri: http://localhost:8080/oauth/token_key  # uri 인증방식
                #key-value: jwt_key_test                        # key-value 인증방식
---

# Server Setting
server :
    session :
        timeout : 1800
    tomcat :
        uri-encoding : UTF-8
    servlet-path : /*
    port: 9091

spring:
    profiles: local
    first :
        datasource:
            url : jdbc:mysql://localhost:3306/OAUTH_PRO?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000
    second :
        datasource:
            url : jdbc:mysql://localhost:3306/OAUTH_PRO?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000
    #jpa:
      #hibernate:
        #ddl-auto: none
        #naming:
          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #show-sql: false


# Actuator 읽기 인증 제거
management :
    security :
        enabled : false


---

# Server Setting
server :
    session :
        timeout : 1800
    tomcat :
        uri-encoding : UTF-8
    servlet-path : /*
    port: 9091

spring:
    profiles: dev
    first :
        datasource:
            url : jdbc:mysql://localhost:3306/OAUTH_PRO?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000
    second :
        datasource:
            url : jdbc:mysql://localhost:3306/OAUTH_PRO?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000
    #jpa:
      #hibernate:
        #ddl-auto: none
        #naming:
          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #show-sql: false


# Actuator 읽기 인증 제거
management :
    security :
        enabled : false